data_dir: /home/xy_th/Project_protein_aggregation/data/rocklin

model_version: v2
model_v2:
  hidden_dim: 512
  n_heads: 8
  n_layers: 2
  dropout: 0.25

train:
  save_dir: results/
  lr: 3e-5
  batch_size: 64
  num_workers: 4
  patience: 15
  epochs: 100

  monitor_metric: val_spearman
  use_scheduler: true
  scheduler:
    name: ReduceLROnPlateau
    mode: max
    factor: 0.5
    patience: 5
    min_lr: 1e-7

hardware:
  accelerator: gpu
  devices: [3]
  precision: 32
